/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_brooklynxu_myapplication_MainActivity */

#ifndef _Included_com_example_brooklynxu_myapplication_MainActivity
#define _Included_com_example_brooklynxu_myapplication_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_brooklynxu_myapplication_MainActivity
 * Method:    getCdromTrackCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_brooklynxu_myapplication_MainActivity_getCdromTrackCount
  (JNIEnv *, jobject);

/*
 * Class:     com_example_brooklynxu_myapplication_MainActivity
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_brooklynxu_myapplication_MainActivity_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_example_brooklynxu_myapplication_MainActivity
 * Method:    setCdromFd
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_brooklynxu_myapplication_MainActivity_setCdromFd
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_brooklynxu_myapplication_MainActivity
 * Method:    grabCdromTrackByNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_brooklynxu_myapplication_MainActivity_grabCdromTrackByNumber
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
